# Generated by Django 4.1.3 on 2023-01-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
