# Generated by Django 4.1.3 on 2022-11-28 08:46

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
